project_id = "tizmocegplamrmpfxvdu"

[functions.logo-proxy]
verify_jwt = false

[functions.realtime-subtitles]
verify_jwt = false

[functions.scrape-live-matches]
verify_jwt = false

[functions.auto-assign-links]
verify_jwt = false

[functions.sync-event-status]
verify_jwt = false
